#!/usr/bin/bash






sudo systemctl enable bluetooth.service

# .fonts
print_colored_and_exec "sudo cp -fvr /home/alexzander/install_manjaro/.fonts /home/alexzander/.fonts"
print_colored_and_exec "tree /home/alexzander/.fonts"

pause_execution



# appending python path to .profile
print_colored_and_exec "sudo echo 'export PYTHONPATH=\$PYTHONPATH:/home/alexzander/Alexzander__/programming/python' >> /home/alexzander/.profile"
print_colored_and_exec "cat /home/alexzander/.profile"
printf "\n"

pause_execution

# overwrites the .bashrc with custom
print_colored_and_exec "sudo cp -fv /home/alexzander/install_manjaro/.bashrc /home/alexzander/.bashrc"
print_colored_and_exec "cat /home/alexzander/.bashrc"
printf "\n"

pause_execution


# .check_path.py for .bashrc
print_colored_and_exec "sudo chmod u+x /home/alexzander/install_manjaro/.check_path.py"
print_colored_and_exec "sudo cp -fv /home/alexzander/install_manjaro/.check_path.py /home/alexzander/.check_path.py"
print_colored_and_exec "cat /home/alexzander/.check_path.py"
printf "\n"

pause_execution


# google search monitor
print_colored_and_exec "sudo chmod u+x /home/alexzander/install_manjaro/google_search_monitor"
print_colored_and_exec "sudo cp -fv /home/alexzander/install_manjaro/google_search_monitor /home/alexzander/google_search_monitor"
print_colored_and_exec "sudo cp -fv /home/alexzander/install_manjaro/google_search_monitor /usr/bin"
print_colored_and_exec "cat /home/alexzander/google_search_monitor"
printf "\n"

pause_execution


# .strip_bash_command.py for .bashrc
print_colored_and_exec "sudo chmod u+x /home/alexzander/install_manjaro/.strip_bash_command.py"
print_colored_and_exec "sudo cp -fv /home/alexzander/install_manjaro/.strip_bash_command.py /home/alexzander/.strip_bash_command.py"
print_colored_and_exec "cat /home/alexzander/.strip_bash_command.py"
printf "\n"

pause_execution


# .netrc
print_colored_and_exec "sudo cp -fv /home/alexzander/install_manjaro/.netrc /home/alexzander/.netrc"
print_colored_and_exec "sudo cat /home/alexzander/.netrc"
printf "\n"

pause_execution

# ftp alexzander.tech auto login
print_colored_and_exec "sudo chmod u+x /home/alexzander/install_manjaro/ftp_alexzander_tech"
print_colored_and_exec "sudo cp -v /home/alexzander/install_manjaro/ftp_alexzander_tech /home/alexzander/ftp_alexzander_tech"
# in order to access by just writing its name without ./
print_colored_and_exec "sudo cp -v /home/alexzander/install_manjaro/ftp_alexzander_tech /usr/bin"
print_colored_and_exec "cat /home/alexzander/ftp_alexzander_tech"
printf "\n"

pause_execution


# my custom copy function
print_colored_and_exec "sudo chmod u+x /home/alexzander/install_manjaro/copy"
print_colored_and_exec "sudo cp -fv /home/alexzander/install_manjaro/copy /home/alexzander/copy"
# in order to access by just writing its name without ./
print_colored_and_exec "sudo cp -v /home/alexzander/install_manjaro/copy /usr/bin"
print_colored_and_exec "cat /home/alexzander/copy"
printf "\n"

pause_execution

# ssh manjaro sony device
print_colored_and_exec "sudo chmod u+x /home/alexzander/install_manjaro/ssh_to_manjaro_sony"
print_colored_and_exec "sudo cp -v /home/alexzander/install_manjaro/ssh_to_manjaro_sony /home/alexzander/ssh_to_manjaro_sony"
# in order to access by just writing its name without ./
print_colored_and_exec "sudo cp -v /home/alexzander/install_manjaro/ssh_to_manjaro_sony /usr/bin"
print_colored_and_exec "cat /home/alexzander/ssh_to_manjaro_sony"
printf "\n"

pause_execution





# remove Applications__ folder
if [[ -d "Applications__" ]]; then
    echo "'Applications__' exists. removing... and creating again"
    print_colored_and_exec "sudo rm -rf Applications__"

    print_colored_and_exec "mkdir Applications__" # empty
    print_colored_and_exec "mkdir Applications__/shell" # empty
    print_colored_and_exec "mkdir Applications__/PythonApplications" # empty
else
    echo "'Applications__' not found ... creating"
    print_colored_and_exec "mkdir Applications__" # empty
    print_colored_and_exec "mkdir Applications__/shell" # empty
    print_colored_and_exec "mkdir Applications__/PythonApplications" # empty
fi



pause_execution



# sshd
print_colored_and_exec "sudo systemctl enable sshd.service"
print_colored_and_exec "sudo systemctl start sshd.service"



# python modules
print_colored_and_exec "pip install pyinstaller playsound pyperclip opencv-python colored_traceback wave pydub gtts pyttsx3 pytesseract numpy matplotlib bs4 numba pyzbar notify2 pytz SpeechRecognition requests_html datedelta tqdm selenium imageio pyautogui moviepy pyowm jedi buildozer Pillow pynput pyaudio youtube_dl"


pause_execution


# bootiso
print_colored_and_exec "cd /home/alexzander/Applications__"
print_colored_and_exec "git clone --branch latest https://github.com/jsamr/bootiso.git"
print_colored_and_exec "cd bootiso"
print_colored_and_exec "sudo make install"


pause_execution


# install vs code
print_colored_and_exec "cd /home/alexzander/Applications__"
print_colored_and_exec "wget https://alexzander.tech/wget/code.tar.gz"
print_colored_and_exec "tar -xzvf code.tar.gz" # nu e -C pentru ca are el folderul lui
print_colored_and_exec "sudo cp -v /home/alexzander/install_manjaro/vscode.desktop /usr/share/applications" # acum se vede la search
print_colored_and_exec "sudo cat /usr/share/applications/vscode.desktop"
printf "\n"


pause_execution


# install dmenu
print_colored_and_exec "cd /home/alexzander/Applications__"
print_colored_and_exec "wget https://alexzander.tech/wget/dmenu.tar.gz"
print_colored_and_exec "mkdir dmenu.5.0"
print_colored_and_exec "tar -zxvf dmenu.tar.gz -C dmenu.5.0"
print_colored_and_exec "cd dmenu.5.0 && sudo make clean install"
# xbindkeysrc for dmenu (CONTROL + SHIFT + D)
print_colored_and_exec "sudo cp -v /home/alexzander/install_manjaro/.xbindkeysrc /home/alexzander/.xbindkeysrc"
print_colored_and_exec "cat /home/alexzander/.xbindkeysrc"
printf "\n"

pause_execution



# install 202020Rule
print_colored_and_exec "cd /home/alexzander/Applications__/PythonApplications"
print_colored_and_exec "wget https://alexzander.tech/wget/202020Rule.tar.gz"
print_colored_and_exec "mkdir 202020Rule && tar -zxvf 202020Rule.tar.gz -C 202020Rule && cd 202020Rule"
print_colored_and_exec "sudo cp -v ./202020Rule.desktop /home/alexzander/.config/autostart/"
print_colored_and_exec "sudo cp -v ./202020Rule.sh /home/alexzander/Applications__/shell"


pause_execution


# install uptime
print_colored_and_exec "cd /home/alexzander/Applications__/PythonApplications"
print_colored_and_exec "wget https://alexzander.tech/wget/uptime.tar.gz"
print_colored_and_exec "mkdir uptime && tar -zxvf uptime.tar.gz -C uptime && cd uptime"
print_colored_and_exec "sudo cp -v ./uptime.desktop /home/alexzander/.config/autostart/"
print_colored_and_exec "sudo cp -v ./uptime.sh /home/alexzander/Applications__/shell"

pause_execution


# install PsaltireaReminder
print_colored_and_exec "cd /home/alexzander/Applications__/PythonApplications"
print_colored_and_exec "wget https://alexzander.tech/wget/PsaltireaReminder.tar.gz"
print_colored_and_exec "mkdir PsaltireaReminder && tar -zxvf PsaltireaReminder.tar.gz -C PsaltireaReminder && cd PsaltireaReminder"
print_colored_and_exec "sudo cp -v ./PsaltireaReminder.desktop /home/alexzander/.config/autostart/"
print_colored_and_exec "sudo cp -v ./PsaltireaReminder.sh /home/alexzander/Applications__/shell"

pause_execution


print_colored_and_exec "cp -fv /home/alexzander/install_manjaro/atom-packages-list.txt /home/alexzander/atom-packages-list.txt"
print_colored_and_exec "apm install --packages-file /home/alexzander/atom-packages-list.txt"

pause_execution


print_colored_and_exec "sudo pamac build teamviewer --no-confirm"
print_colored_and_exec "sudo teamviewer --daemon start"


function reboot_prompt () {
    read -p "$(echo -e "${b}\n[press${e} ${GREEN}${b}<enter>${e} ${b}to reboot]:${e} ")"
}

reboot_prompt
echo -e "\nrebooting... in 2 seconds."
sleep 2
reboot

