#!/usr/bin/bash

source "`ueberzug library`"

image_path=$1
height=$(identify $image_path | cut -f 3 -d " " | cut -f 1 -d "x")
width=$(identify $image_path | cut -f 3 -d " " | cut -f 2 -d "x")

ImageLayer 0< <(
    ImageLayer::add [identifier]="example0" [x]="0" [y]="0" [max_width]="1800" [max_height]="900" [path]="$image_path"
    read
)
